server:
  port: 8008

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/zy_prod?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cafuc.flyeat.zy.model

prop:
  upload-path: C:/ZY_upload/